edition = "2018"

unstable_features = true
merge_imports = true

max_width = 120
array_width = 80
indent_style = "Block"
reorder_imports = true
reorder_modules = true
merge_derives = false
use_small_heuristics = "Max"

error_on_line_overflow = true
error_on_unformatted = true

ignore = []
